language: node_js

node_js:
  - "14.17.3"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing JWT_SECRET=secret_token
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookstest;" -U postgres
  - npm run migrations-test

script:
  - npm run lint
  - npm run test
